#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
##
## Autostart Programs

# Kill already running process
_ps=(waybar mako mpd gnome-keyring-daemon) # used to have xfce-polkit here
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Polkit agent
#/usr/lib/xfce-polkit/xfce-polkit &
if [ -n "$DESKTOP_SESSION" ];then
    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
fi

# Lauch notification daemon (mako)
~/.config/sway/scripts/notifications &

# Lauch statusbar (waybar)
~/.config/sway/scripts/statusbar &

# Start mpd
exec mpd &

# My Startup Apps
nextcloud --background
bitwarden
flameshot